title: TSX.AI Documentation
description: Internal documentation for TSX.AI market intelligence platform
theme: jekyll-theme-minimal

# GitHub Pages configuration
baseurl: "" 
url: ""

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Navigation
show_downloads: false
google_analytics: