# Jekyll configuration for GitHub Pages
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: TSX.AI Platform
description: Real-time market intelligence for Canadian stocks
show_downloads: false

# Markdown processing
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge